
import json
from pathlib import Path
from datetime import datetime, timezone

def restore_skills():
    skills_path = Path('skills.json')
    with open(skills_path, 'r', encoding='utf-8') as f:
        skills = json.load(f)

    existing_ids = {s['id'] for s in skills}
    now = datetime.now(timezone.utc).isoformat()

    new_skills = [
        # --- High-Value Skills ---
        {
            "id": "skill-ai-security",
            "name": "AI 安全与防御 (OWASP)",
            "slug": "ai-security-owasp",
            "description": "基于 OWASP Top 10 的 LLM 安全指南，防御提示词注入和数据泄露。",
            "longDescription": "专注于 LLM 应用安全的必备技能。\n**核心能力：**\n- **防御提示词注入**：识别和拦截 Jailbreak 攻击。\n- **隐私保护**：防止 PII 泄露。\n- **输出过滤**：过滤恶意内容。",
            "category": "ai-ml",
            "tags": ["security", "owasp", "safety"],
            "platforms": ["cursor", "claude", "kiro", "windsurf", "trae", "copilot", "antigravity", "codex"],
            "languages": ["python", "javascript", "general"],
            "complexity": "advanced",
            "author": {"name": "Community", "url": ""},
            "sourceRepo": "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
            "lastUpdated": now,
            "usageType": "instruction",
            "featured": True,
            "popular": False,
            "icon": "🛡️",
            "systemPrompt": "You are an AI Security Expert specialized in the OWASP Top 10 for LLM Applications. Analyze the provided code for vulnerabilities."
        },
        {
            "id": "skill-prompt-engineering-advanced",
            "name": "提示词工程进阶",
            "slug": "advanced-prompt-engineering",
            "description": "掌握 CoT, ReAct, Few-Shot 等高级提示词技巧。",
            "longDescription": "从入门到精通的提示词工程指南。\n**核心技术：**\n- **CoT (思维链)**：引导模型分步思考。\n- **Few-Shot**：提供示例规范输出。\n- **ReAct 框架**：结合推理和行动。",
            "category": "ai-ml",
            "tags": ["prompt-engineering", "cot", "react"],
            "platforms": ["cursor", "claude", "kiro", "windsurf", "trae", "copilot", "antigravity", "codex"],
            "languages": ["general"],
            "complexity": "intermediate",
            "author": {"name": "Community", "url": ""},
            "sourceRepo": "https://github.com/dair-ai/Prompt-Engineering-Guide",
            "lastUpdated": now,
            "usageType": "instruction",
            "featured": True,
            "popular": True,
            "icon": "🗣️",
            "systemPrompt": "You are a Prompt Engineering Instructor. Help optimize prompts using CoT, Few-Shot, and ReAct techniques."
        },
        {
            "id": "skill-auto-docs",
            "name": "自动文档专家",
            "slug": "auto-docs",
            "description": "强制 AI 生成符合 JSDoc/Google Style 标准的高质量代码文档。",
            "longDescription": "拒绝无文档代码。\n**核心能力：**\n- 根据语言自动选择 JSDoc, PyDoc, GoDoc。\n- 在文档中明确参数类型和返回值。\n- 自动为复杂函数生成 Usage Example。",
            "category": "tools",
            "tags": ["documentation", "jsdoc", "pydoc"],
            "platforms": ["cursor", "claude", "kiro", "windsurf", "trae", "copilot", "antigravity", "codex"],
            "languages": ["python", "javascript", "typescript", "go", "java"],
            "complexity": "beginner",
            "author": {"name": "Community", "url": ""},
            "sourceRepo": "https://google.github.io/styleguide/pyguide.html",
            "lastUpdated": now,
            "usageType": "instruction",
            "featured": False,
            "popular": True,
            "icon": "📝",
            "systemPrompt": "You are a Technical Documentation Expert. Generate comprehensive JSDoc/PyDoc for provided code."
        },
        {
            "id": "skill-design-patterns",
            "name": "设计模式",
            "slug": "design-patterns",
            "description": "在项目中正确实现 GoF 23 种设计模式的最佳实践。",
            "longDescription": "将经典软件工程智慧赋予 AI。\n**包含模式：**\n- **创建型**：单例、工厂、建造者。\n- **结构型**：适配器、装饰器、代理。\n- **行为型**：观察者、策略、状态。",
            "category": "backend",
            "tags": ["design-patterns", "architecture", "refactoring"],
            "platforms": ["cursor", "claude", "kiro", "windsurf", "trae", "copilot", "antigravity", "codex"],
            "languages": ["java", "python", "typescript", "cpp", "csharp"],
            "complexity": "advanced",
            "author": {"name": "Gang of Four", "url": ""},
            "sourceRepo": "https://refactoring.guru/design-patterns",
            "lastUpdated": now,
            "usageType": "instruction",
            "featured": True,
            "popular": True,
            "icon": "🏗️",
            "systemPrompt": "You are a Senior Software Architect. Recommend appropriate Design Patterns and provide implementation examples."
        },
        # --- AI Coding Tools ---
        {
            "id": "skill-cline",
            "name": "Cline",
            "slug": "cline",
            "description": "VS Code 的自主编程 Agent 插件。",
            "longDescription": "Cline 是一个驻留在 IDE (VS Code) 中的自主编程 Agent。\n**核心能力：**\n- 自主任务执行\n- 文件操作、终端、浏览器工具\n- 多模型支持 (Claude, GPT-4o)",
            "category": "tools",
            "tags": ["agent", "vscode", "autonomous"],
            "platforms": ["cursor", "vscode", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["typescript"],
            "complexity": "advanced",
            "author": {"name": "Cline", "url": "https://github.com/cline"},
            "sourceRepo": "https://github.com/cline/cline",
            "lastUpdated": now,
            "usageType": "tool",
            "featured": True,
            "popular": True,
            "icon": "🤖",
            "systemPrompt": "You are an expert on Cline. Help users configure and use Cline effectively."
        },
        {
            "id": "skill-aider",
            "name": "Aider",
            "slug": "aider",
            "description": "终端里的 AI 结对编程工具。",
            "longDescription": "Aider 是命令行 AI 编程工具。\n**核心能力：**\n- Git 集成自动提交\n- 代码库理解 (Repo Map)\n- 多文件编辑",
            "category": "tools",
            "tags": ["agent", "terminal", "cli"],
            "platforms": ["cursor", "claude", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["python"],
            "complexity": "intermediate",
            "author": {"name": "Aider-AI", "url": "https://github.com/aider-AI"},
            "sourceRepo": "https://github.com/aider-AI/aider",
            "lastUpdated": now,
            "usageType": "tool",
            "featured": True,
            "popular": True,
            "icon": "💻",
            "systemPrompt": "You are an expert on Aider. Help users with terminal-based AI pair programming."
        },
        {
            "id": "skill-continue",
            "name": "Continue",
            "slug": "continue",
            "description": "用于 VS Code 和 JetBrains 的开源 AI 代码助手。",
            "longDescription": "Continue 是开源 AI 代码助手。\n**核心能力：**\n- 上下文感知聊天\n- Tab 自动补全\n- 自定义模型 (Ollama, LM Studio)",
            "category": "tools",
            "tags": ["assistant", "vscode", "jetbrains"],
            "platforms": ["vscode", "jetbrains", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["typescript", "python"],
            "complexity": "intermediate",
            "author": {"name": "Continue", "url": "https://github.com/continuedev"},
            "sourceRepo": "https://github.com/continuedev/continue",
            "lastUpdated": now,
            "usageType": "tool",
            "featured": True,
            "popular": True,
            "icon": "⏩",
            "systemPrompt": "You are an expert on Continue. Help users set up and customize their AI coding environment."
        },
        {
            "id": "skill-openhands",
            "name": "OpenHands",
            "slug": "openhands",
            "description": "AI 软件工程师，能够编写代码、修复 Bug 并部署应用。",
            "longDescription": "OpenHands (前 OpenDevin) 是自主 AI 软件工程师。\n**核心能力：**\n- 全栈开发\n- 沙箱环境\n- 可视化 Web UI",
            "category": "ai-ml",
            "tags": ["agent", "autonomous", "engineer"],
            "platforms": ["claude", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["python", "typescript"],
            "complexity": "advanced",
            "author": {"name": "All-Hands-AI", "url": "https://github.com/All-Hands-AI"},
            "sourceRepo": "https://github.com/All-Hands-AI/OpenHands",
            "lastUpdated": now,
            "usageType": "tool",
            "featured": True,
            "popular": True,
            "icon": "👐",
            "systemPrompt": "You are an expert on OpenHands. Help users build and deploy applications with this AI agent."
        },
        {
            "id": "skill-autogpt",
            "name": "AutoGPT",
            "slug": "autogpt",
            "description": "让 GPT-4 完全自主化的实验性开源尝试。",
            "longDescription": "AutoGPT 是自主 AI Agent 先驱。\n**核心能力：**\n- 目标拆解\n- 联网搜索\n- 长期记忆",
            "category": "ai-ml",
            "tags": ["agent", "autonomous", "gpt-4"],
            "platforms": ["claude", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["python"],
            "complexity": "advanced",
            "author": {"name": "Significant Gravitas", "url": "https://github.com/Significant-Gravitas"},
            "sourceRepo": "https://github.com/Significant-Gravitas/Auto-GPT",
            "lastUpdated": now,
            "usageType": "repository",
            "featured": True,
            "popular": True,
            "icon": "🏎️",
            "systemPrompt": "You are an expert on AutoGPT. Help users understand autonomous AI agent concepts."
        },
        {
            "id": "skill-langchain",
            "name": "LangChain",
            "slug": "langchain",
            "description": "通过可组合性构建 LLM 应用程序。",
            "longDescription": "LangChain 是构建 LLM 应用的标准框架。\n**核心能力：**\n- 链式调用 (Chains)\n- 记忆 (Memory)\n- RAG 支持",
            "category": "ai-ml",
            "tags": ["framework", "llm", "python"],
            "platforms": ["cursor", "claude", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["python", "javascript"],
            "complexity": "intermediate",
            "author": {"name": "LangChain", "url": "https://github.com/langchain-ai"},
            "sourceRepo": "https://github.com/langchain-ai/langchain",
            "lastUpdated": now,
            "usageType": "framework",
            "featured": True,
            "popular": True,
            "icon": "🦜",
            "systemPrompt": "You are a LangChain Expert. Help build LLM applications with Chains, Agents, and Retrievers."
        },
        {
            "id": "skill-llamaindex",
            "name": "LlamaIndex",
            "slug": "llamaindex",
            "description": "LLM 应用的数据框架，用于连接私有数据。",
            "longDescription": "LlamaIndex 用于构建 RAG 应用。\n**核心能力：**\n- 数据连接器\n- 索引结构\n- 查询引擎",
            "category": "ai-ml",
            "tags": ["framework", "rag", "data"],
            "platforms": ["cursor", "claude", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["python"],
            "complexity": "intermediate",
            "author": {"name": "LlamaIndex", "url": "https://github.com/run-llama"},
            "sourceRepo": "https://github.com/run-llama/llama_index",
            "lastUpdated": now,
            "usageType": "framework",
            "featured": True,
            "popular": True,
            "icon": "🦙",
            "systemPrompt": "You are a LlamaIndex Expert. Help build RAG applications with data connectors and query engines."
        },
        {
            "id": "skill-crewai",
            "name": "CrewAI",
            "slug": "crewai",
            "description": "用于编排角色扮演型 AI Agent 的框架。",
            "longDescription": "CrewAI 用于多 Agent 协作。\n**核心能力：**\n- 角色定义\n- 任务分配\n- 协作流程",
            "category": "ai-ml",
            "tags": ["framework", "agents", "orchestration"],
            "platforms": ["cursor", "claude", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["python"],
            "complexity": "advanced",
            "author": {"name": "CrewAI", "url": "https://github.com/crewAIInc"},
            "sourceRepo": "https://github.com/crewAIInc/crewAI",
            "lastUpdated": now,
            "usageType": "framework",
            "featured": True,
            "popular": True,
            "icon": "👥",
            "systemPrompt": "You are a CrewAI Expert. Help build multi-agent systems with role-based collaboration."
        },
        {
            "id": "skill-vercel-ai-sdk",
            "name": "Vercel AI SDK",
            "slug": "vercel-ai-sdk",
            "description": "用于构建 AI 应用的 TypeScript 工具包。",
            "longDescription": "Vercel AI SDK 是 TypeScript AI 开发工具。\n**核心能力：**\n- 流式响应\n- React Hooks\n- 多模型支持",
            "category": "frontend",
            "tags": ["sdk", "typescript", "react"],
            "platforms": ["cursor", "claude", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["typescript", "javascript"],
            "complexity": "intermediate",
            "author": {"name": "Vercel", "url": "https://github.com/vercel"},
            "sourceRepo": "https://github.com/vercel/ai",
            "lastUpdated": now,
            "usageType": "sdk",
            "featured": False,
            "popular": True,
            "icon": "▲",
            "systemPrompt": "You are a Vercel AI SDK Expert. Help build AI-powered web apps with streaming and React."
        },
        {
            "id": "skill-superagi",
            "name": "SuperAGI",
            "slug": "superagi",
            "description": "自主 AI Agent 框架，支持自定义工具和工作流。",
            "longDescription": "SuperAGI 是 Agent 开发框架。\n**核心能力：**\n- 工具市场\n- 向量存储\n- GUI 管理界面",
            "category": "ai-ml",
            "tags": ["framework", "agents", "autonomous"],
            "platforms": ["claude", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["python"],
            "complexity": "advanced",
            "author": {"name": "SuperAGI", "url": "https://github.com/TransformerOptimus"},
            "sourceRepo": "https://github.com/TransformerOptimus/SuperAGI",
            "lastUpdated": now,
            "usageType": "framework",
            "featured": False,
            "popular": False,
            "icon": "🦸",
            "systemPrompt": "You are a SuperAGI Expert. Help build autonomous AI agents with custom tools."
        },
        {
            "id": "skill-gpt-engineer",
            "name": "GPT Engineer",
            "slug": "gpt-engineer",
            "description": "描述你想要的，AI 会询问细节并开始构建。",
            "longDescription": "GPT Engineer 是对话式代码生成器。\n**核心能力：**\n- 需求澄清\n- 代码生成\n- 迭代改进",
            "category": "ai-ml",
            "tags": ["agent", "code-generation", "autonomous"],
            "platforms": ["claude", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["python"],
            "complexity": "intermediate",
            "author": {"name": "GPT Engineer", "url": "https://github.com/gpt-engineer-org"},
            "sourceRepo": "https://github.com/gpt-engineer-org/gpt-engineer",
            "lastUpdated": now,
            "usageType": "tool",
            "featured": False,
            "popular": True,
            "icon": "🔧",
            "systemPrompt": "You are a GPT Engineer Expert. Help users generate code through conversational AI."
        },
        {
            "id": "skill-metagpt",
            "name": "MetaGPT",
            "slug": "metagpt",
            "description": "多 Agent 框架，模拟软件公司的工作流程。",
            "longDescription": "MetaGPT 模拟软件开发团队。\n**核心能力：**\n- 角色分工 (PM, Architect, Engineer)\n- SOP 流程\n- 文档生成",
            "category": "ai-ml",
            "tags": ["framework", "multi-agent", "sop"],
            "platforms": ["claude", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["python"],
            "complexity": "advanced",
            "author": {"name": "MetaGPT", "url": "https://github.com/geekan"},
            "sourceRepo": "https://github.com/geekan/MetaGPT",
            "lastUpdated": now,
            "usageType": "framework",
            "featured": True,
            "popular": True,
            "icon": "🏢",
            "systemPrompt": "You are a MetaGPT Expert. Help build multi-agent systems mimicking software company workflows."
        },
        {
            "id": "skill-autogen",
            "name": "Microsoft AutoGen",
            "slug": "autogen",
            "description": "用于多 Agent 对话的框架。",
            "longDescription": "AutoGen 是微软的多 Agent 框架。\n**核心能力：**\n- Agent 对话\n- 代码执行\n- 人机协作",
            "category": "ai-ml",
            "tags": ["framework", "multi-agent", "microsoft"],
            "platforms": ["claude", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["python"],
            "complexity": "intermediate",
            "author": {"name": "Microsoft", "url": "https://github.com/microsoft"},
            "sourceRepo": "https://github.com/microsoft/autogen",
            "lastUpdated": now,
            "usageType": "framework",
            "featured": True,
            "popular": True,
            "icon": "🪟",
            "systemPrompt": "You are an AutoGen Expert. Help build conversational multi-agent applications."
        },
        {
            "id": "skill-haystack",
            "name": "Haystack",
            "slug": "haystack",
            "description": "用于构建 NLP 管道的框架。",
            "longDescription": "Haystack 是 NLP 管道框架。\n**核心能力：**\n- 文档检索\n- QA 系统\n- RAG 管道",
            "category": "ai-ml",
            "tags": ["framework", "nlp", "rag"],
            "platforms": ["cursor", "claude", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["python"],
            "complexity": "intermediate",
            "author": {"name": "deepset", "url": "https://github.com/deepset-ai"},
            "sourceRepo": "https://github.com/deepset-ai/haystack",
            "lastUpdated": now,
            "usageType": "framework",
            "featured": False,
            "popular": True,
            "icon": "🔍",
            "systemPrompt": "You are a Haystack Expert. Help build NLP pipelines and RAG systems."
        },
        {
            "id": "skill-taskweaver",
            "name": "TaskWeaver",
            "slug": "taskweaver",
            "description": "代码优先的 Agent 框架。",
            "longDescription": "TaskWeaver 是微软的代码优先 Agent。\n**核心能力：**\n- 代码生成\n- 插件系统\n- 状态管理",
            "category": "ai-ml",
            "tags": ["framework", "code-first", "microsoft"],
            "platforms": ["claude", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["python"],
            "complexity": "advanced",
            "author": {"name": "Microsoft", "url": "https://github.com/microsoft"},
            "sourceRepo": "https://github.com/microsoft/TaskWeaver",
            "lastUpdated": now,
            "usageType": "framework",
            "featured": False,
            "popular": False,
            "icon": "🧵",
            "systemPrompt": "You are a TaskWeaver Expert. Help build code-first AI agents."
        },
        {
            "id": "skill-babyagi",
            "name": "BabyAGI",
            "slug": "babyagi",
            "description": "简单的自主 Agent 原型。",
            "longDescription": "BabyAGI 是极简自主 Agent。\n**核心能力：**\n- 任务管理\n- 优先级排序\n- 循环执行",
            "category": "ai-ml",
            "tags": ["agent", "autonomous", "simple"],
            "platforms": ["claude", "kiro", "trae", "windsurf", "copilot", "antigravity", "codex"],
            "languages": ["python"],
            "complexity": "beginner",
            "author": {"name": "yoheinakajima", "url": "https://github.com/yoheinakajima"},
            "sourceRepo": "https://github.com/yoheinakajima/babyagi",
            "lastUpdated": now,
            "usageType": "repository",
            "featured": False,
            "popular": True,
            "icon": "👶",
            "systemPrompt": "You are a BabyAGI Expert. Help understand simple autonomous agent concepts."
        }
    ]

    added = 0
    for skill in new_skills:
        if skill['id'] not in existing_ids:
            skills.append(skill)
            added += 1

    with open(skills_path, 'w', encoding='utf-8') as f:
        json.dump(skills, f, ensure_ascii=False, indent=2)

    print(f"Restored {added} skills. Total: {len(skills)}")

if __name__ == "__main__":
    restore_skills()
